version: "3"

services:
  dfs:
    build:
      context: .
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - db
      - validator_service
    networks:
      - dfsnet
    environment:
      - RAILS_LOG_TO_STDOUT=true
    volumes:
      - ./db/seeds:/home/app/dfs/db/seeds:ro
  db:
    image: postgres:12-alpine
    volumes:
      - dfs-pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGPASSWORD=dfspass1
    restart: unless-stopped
    networks:
      - dfsnet
  validator_service:
    image: infernocommunity/fhir-validator-service:latest
    restart: unless-stopped
    networks:
      - dfsnet

networks:
  dfsnet:

volumes:
  dfs-pgdata:
